package ch.bebaforst.forestnet.UI;



import ch.bebaforst.forestnet.data.Kunde;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.navigator.Navigator;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Notification;

@SuppressWarnings("serial")
public class ModuleSelect extends CustomComponent implements View {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Button button_6;
	@AutoGenerated
	private Label label_2;
	@AutoGenerated
	private Label label_1;
	@AutoGenerated
	private Button button_5;
	@AutoGenerated
	private Button button_4;
	@AutoGenerated
	private Button button_3;
	@AutoGenerated
	private Button button_2;
	@AutoGenerated
	private Button button_1;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 * @param navigator 
	 */
	Navigator navigator;
	
	
	
	public ModuleSelect(Navigator navigator) {
		this.navigator=navigator;
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@Override
	public void enter(ViewChangeEvent event) {
//		Notification.show("Entered in das andere Ding");
		Kunde kunde = new Kunde();
		kunde.setName("Muster");
		kunde.setVorname("Max");
		kunde.save();
		System.out.println("Kunde erstellt");
		Notification.show("Kunde erstellt");

	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// button_1
		button_1 = new Button();
		button_1.setCaption("sonst noch was");
		button_1.setImmediate(true);
		button_1.setWidth("140px");
		button_1.setHeight("-1px");
		mainLayout.addComponent(button_1, "top:274.0px;left:20.0px;");
		
		// button_2
		button_2 = new Button();
		button_2.setCaption("Holzaufnahme");
		button_2.setImmediate(true);
		button_2.setWidth("140px");
		button_2.setHeight("-1px");
		button_2.addClickListener(new ClickListener() {
			
			@Override
			public void buttonClick(ClickEvent event) {
				Notification.show("Vielleicht ensteht da mal die Holzaufnahme");

			}
		});
		mainLayout.addComponent(button_2, "top:100.0px;left:20.0px;");
		
		// button_3
		button_3 = new Button();
		button_3.setCaption("Stundenrapport");
		button_3.setImmediate(true);
		button_3.setWidth("140px");
		button_3.setHeight("-1px");
		button_3.addClickListener(new ClickListener() {
			
			@Override
			public void buttonClick(ClickEvent event) {
				navigator.navigateTo("stdRapp");
			}
		});
		mainLayout.addComponent(button_3, "top:60.0px;left:20.0px;");
		
		// button_4
		button_4 = new Button();
		button_4.setCaption("Auftrag erfassen");
		button_4.setImmediate(true);
		button_4.setWidth("140px");
		button_4.setHeight("-1px");
		mainLayout.addComponent(button_4, "top:140.0px;left:20.0px;");
		
		// button_5
		button_5 = new Button();
		button_5.setCaption("Allerlei");
		button_5.setImmediate(true);
		button_5.setWidth("140px");
		button_5.setHeight("-1px");
		mainLayout.addComponent(button_5, "top:234.0px;left:20.0px;");
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("140px");
		label_1.setHeight("-1px");
		label_1.setValue("Eingabe");
		mainLayout.addComponent(label_1, "top:20.0px;left:20.0px;");
		
		// label_2
		label_2 = new Label();
		label_2.setImmediate(false);
		label_2.setWidth("140px");
		label_2.setHeight("-1px");
		label_2.setValue("Verwalten");
		mainLayout.addComponent(label_2, "top:200.0px;left:20.0px;");
		
		// button_6
		button_6 = new Button();
		button_6.setCaption("Logout");
		button_6.setImmediate(false);
		button_6.setWidth("140px");
		button_6.setHeight("-1px");
		button_6.addClickListener(new ClickListener() {
			
			@Override
			public void buttonClick(ClickEvent event) {
			navigator.navigateTo("login");	
			}
		});
		mainLayout.addComponent(button_6, "top:340.0px;left:20.0px;");
		
		return mainLayout;
	}

}
